window.__REPORT_DATA__ = {
  "createdAt": "2026-01-20T20:00:43.006Z",
  "sources": [
    {
      "file": "exp-1",
      "source": "exp-1",
      "createdAt": "2026-01-20T20:00:43.007Z"
    }
  ],
  "summaries": [
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 0.1726,
      "time_ms_std": null,
      "ops_sec_mean": 5793.26,
      "memory_kb_mean": -0.45,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 0.5941,
      "time_ms_std": null,
      "ops_sec_mean": 1683.18,
      "memory_kb_mean": -0.73,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 0.1404,
      "time_ms_std": null,
      "ops_sec_mean": 7124.68,
      "memory_kb_mean": -1.15,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 0.059,
      "time_ms_std": null,
      "ops_sec_mean": 16936.85,
      "memory_kb_mean": -0.57,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 0.1882,
      "time_ms_std": null,
      "ops_sec_mean": 5312.29,
      "memory_kb_mean": -1.2,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 0.0252,
      "time_ms_std": null,
      "ops_sec_mean": 39637.6,
      "memory_kb_mean": -1.18,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 0.0028,
      "time_ms_std": null,
      "ops_sec_mean": 362694.3,
      "memory_kb_mean": -1.23,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 0.0772,
      "time_ms_std": null,
      "ops_sec_mean": 12958.16,
      "memory_kb_mean": -1.26,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 0.0138,
      "time_ms_std": null,
      "ops_sec_mean": 72314.05,
      "memory_kb_mean": -0.83,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 0.0331,
      "time_ms_std": null,
      "ops_sec_mean": 30211.48,
      "memory_kb_mean": -1.15,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 0.023,
      "time_ms_std": null,
      "ops_sec_mean": 43505.28,
      "memory_kb_mean": -1.29,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 0.3851,
      "time_ms_std": null,
      "ops_sec_mean": 2596.73,
      "memory_kb_mean": -1.08,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 0.0814,
      "time_ms_std": null,
      "ops_sec_mean": 12289.33,
      "memory_kb_mean": -1.24,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 0.0143,
      "time_ms_std": null,
      "ops_sec_mean": 70000,
      "memory_kb_mean": -1.14,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 0.0288,
      "time_ms_std": null,
      "ops_sec_mean": 34773.97,
      "memory_kb_mean": -1.14,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 0.0537,
      "time_ms_std": null,
      "ops_sec_mean": 18617.02,
      "memory_kb_mean": -1.57,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 0.0088,
      "time_ms_std": null,
      "ops_sec_mean": 113268.61,
      "memory_kb_mean": -1.05,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 0.0787,
      "time_ms_std": null,
      "ops_sec_mean": 12699.56,
      "memory_kb_mean": -1.32,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 0.0139,
      "time_ms_std": null,
      "ops_sec_mean": 71942.45,
      "memory_kb_mean": -1.05,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 0.0275,
      "time_ms_std": null,
      "ops_sec_mean": 36401.46,
      "memory_kb_mean": -1.24,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 0.1129,
      "time_ms_std": null,
      "ops_sec_mean": 8856.28,
      "memory_kb_mean": -1.57,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 0.1751,
      "time_ms_std": null,
      "ops_sec_mean": 5712.42,
      "memory_kb_mean": -1.05,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 0.085,
      "time_ms_std": null,
      "ops_sec_mean": 11758.78,
      "memory_kb_mean": -1.32,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 0.0288,
      "time_ms_std": null,
      "ops_sec_mean": 34756.7,
      "memory_kb_mean": -1.24,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 0.044,
      "time_ms_std": null,
      "ops_sec_mean": 22749.43,
      "memory_kb_mean": -1.24,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 0.0936,
      "time_ms_std": null,
      "ops_sec_mean": 10678.87,
      "memory_kb_mean": -1.65,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 0.1561,
      "time_ms_std": null,
      "ops_sec_mean": 6404.98,
      "memory_kb_mean": -1.06,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 0.0809,
      "time_ms_std": null,
      "ops_sec_mean": 12363.12,
      "memory_kb_mean": -1.32,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 0.0243,
      "time_ms_std": null,
      "ops_sec_mean": 41079.81,
      "memory_kb_mean": 0.65,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 0.0383,
      "time_ms_std": null,
      "ops_sec_mean": 26099.93,
      "memory_kb_mean": -1.24,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 0.0209,
      "time_ms_std": null,
      "ops_sec_mean": 47814.21,
      "memory_kb_mean": -1.26,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 0.0291,
      "time_ms_std": null,
      "ops_sec_mean": 34313.73,
      "memory_kb_mean": -1.24,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 0.103,
      "time_ms_std": null,
      "ops_sec_mean": 9711.43,
      "memory_kb_mean": -0.57,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 0.0483,
      "time_ms_std": null,
      "ops_sec_mean": 20691.69,
      "memory_kb_mean": -1.27,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 1000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 0.1713,
      "time_ms_std": null,
      "ops_sec_mean": 5836.74,
      "memory_kb_mean": -1.08,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 1.6419,
      "time_ms_std": null,
      "ops_sec_mean": 609.04,
      "memory_kb_mean": -1.1,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 25.6022,
      "time_ms_std": null,
      "ops_sec_mean": 39.06,
      "memory_kb_mean": -11.1,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 1.5926,
      "time_ms_std": null,
      "ops_sec_mean": 627.89,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 0.7276,
      "time_ms_std": null,
      "ops_sec_mean": 1374.38,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 0.8485,
      "time_ms_std": null,
      "ops_sec_mean": 1178.53,
      "memory_kb_mean": -9.92,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 0.1607,
      "time_ms_std": null,
      "ops_sec_mean": 6223.33,
      "memory_kb_mean": -11.2,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 0.0279,
      "time_ms_std": null,
      "ops_sec_mean": 35860.66,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 0.8552,
      "time_ms_std": null,
      "ops_sec_mean": 1169.34,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 0.2182,
      "time_ms_std": null,
      "ops_sec_mean": 4582.65,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 0.362,
      "time_ms_std": null,
      "ops_sec_mean": 2762.54,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 0.1825,
      "time_ms_std": null,
      "ops_sec_mean": 5479.88,
      "memory_kb_mean": -11.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 49.7083,
      "time_ms_std": null,
      "ops_sec_mean": 20.12,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 0.9449,
      "time_ms_std": null,
      "ops_sec_mean": 1058.3,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 0.2254,
      "time_ms_std": null,
      "ops_sec_mean": 4436.56,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 0.3763,
      "time_ms_std": null,
      "ops_sec_mean": 2657.25,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 0.4111,
      "time_ms_std": null,
      "ops_sec_mean": 2432.58,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 0.6762,
      "time_ms_std": null,
      "ops_sec_mean": 1478.85,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 0.9576,
      "time_ms_std": null,
      "ops_sec_mean": 1044.26,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 0.2303,
      "time_ms_std": null,
      "ops_sec_mean": 4342.16,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 0.369,
      "time_ms_std": null,
      "ops_sec_mean": 2709.71,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 0.8253,
      "time_ms_std": null,
      "ops_sec_mean": 1211.74,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 22.4351,
      "time_ms_std": null,
      "ops_sec_mean": 44.57,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 1.0081,
      "time_ms_std": null,
      "ops_sec_mean": 991.94,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 0.3976,
      "time_ms_std": null,
      "ops_sec_mean": 2514.82,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 0.5296,
      "time_ms_std": null,
      "ops_sec_mean": 1888.12,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 0.752,
      "time_ms_std": null,
      "ops_sec_mean": 1329.79,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 20.1008,
      "time_ms_std": null,
      "ops_sec_mean": 49.75,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 0.9908,
      "time_ms_std": null,
      "ops_sec_mean": 1009.24,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 0.3605,
      "time_ms_std": null,
      "ops_sec_mean": 2774.04,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 0.4839,
      "time_ms_std": null,
      "ops_sec_mean": 2066.6,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 0.1663,
      "time_ms_std": null,
      "ops_sec_mean": 6012.2,
      "memory_kb_mean": -11.2,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 0.0261,
      "time_ms_std": null,
      "ops_sec_mean": 38272.28,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 0.8591,
      "time_ms_std": null,
      "ops_sec_mean": 1164.01,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 0.3178,
      "time_ms_std": null,
      "ops_sec_mean": 3147.06,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 10000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 0.4463,
      "time_ms_std": null,
      "ops_sec_mean": 2240.79,
      "memory_kb_mean": -11.13,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 20.5559,
      "time_ms_std": null,
      "ops_sec_mean": 48.65,
      "memory_kb_mean": -11.16,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 2489.5166,
      "time_ms_std": null,
      "ops_sec_mean": 0.4,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 19.7432,
      "time_ms_std": null,
      "ops_sec_mean": 50.65,
      "memory_kb_mean": -111.6,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 9.0546,
      "time_ms_std": null,
      "ops_sec_mean": 110.44,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 10.1567,
      "time_ms_std": null,
      "ops_sec_mean": 98.46,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 1.9382,
      "time_ms_std": null,
      "ops_sec_mean": 515.95,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 0.5039,
      "time_ms_std": null,
      "ops_sec_mean": 1984.52,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 13.0195,
      "time_ms_std": null,
      "ops_sec_mean": 76.81,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 3.0888,
      "time_ms_std": null,
      "ops_sec_mean": 323.75,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 4.3817,
      "time_ms_std": null,
      "ops_sec_mean": 228.22,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 2.0932,
      "time_ms_std": null,
      "ops_sec_mean": 477.73,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 4977.6082,
      "time_ms_std": null,
      "ops_sec_mean": 0.2,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 13.5938,
      "time_ms_std": null,
      "ops_sec_mean": 73.56,
      "memory_kb_mean": -111.6,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 3.0017,
      "time_ms_std": null,
      "ops_sec_mean": 333.14,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 4.4341,
      "time_ms_std": null,
      "ops_sec_mean": 225.52,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 4.8433,
      "time_ms_std": null,
      "ops_sec_mean": 206.47,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 66.8842,
      "time_ms_std": null,
      "ops_sec_mean": 14.95,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 14.2928,
      "time_ms_std": null,
      "ops_sec_mean": 69.97,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 3.0214,
      "time_ms_std": null,
      "ops_sec_mean": 330.98,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 4.7537,
      "time_ms_std": null,
      "ops_sec_mean": 210.36,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 9.5589,
      "time_ms_std": null,
      "ops_sec_mean": 104.61,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 2240.759,
      "time_ms_std": null,
      "ops_sec_mean": 0.45,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 14.8651,
      "time_ms_std": null,
      "ops_sec_mean": 67.27,
      "memory_kb_mean": -111.6,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 4.7307,
      "time_ms_std": null,
      "ops_sec_mean": 211.38,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 6.1042,
      "time_ms_std": null,
      "ops_sec_mean": 163.82,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 8.7165,
      "time_ms_std": null,
      "ops_sec_mean": 114.72,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 2022.9085,
      "time_ms_std": null,
      "ops_sec_mean": 0.49,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 14.7926,
      "time_ms_std": null,
      "ops_sec_mean": 67.6,
      "memory_kb_mean": -111.6,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 4.6454,
      "time_ms_std": null,
      "ops_sec_mean": 215.27,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 5.6864,
      "time_ms_std": null,
      "ops_sec_mean": 175.86,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 1.9793,
      "time_ms_std": null,
      "ops_sec_mean": 505.22,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "insertion-sort",
      "displayName": "insertion-sort",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 0.4923,
      "time_ms_std": null,
      "ops_sec_mean": 2031.28,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 13.5765,
      "time_ms_std": null,
      "ops_sec_mean": 73.66,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 4.1237,
      "time_ms_std": null,
      "ops_sec_mean": 242.5,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 100000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 5.5738,
      "time_ms_std": null,
      "ops_sec_mean": 179.41,
      "memory_kb_mean": -111.61,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 249.1702,
      "time_ms_std": null,
      "ops_sec_mean": 4.01,
      "memory_kb_mean": -111.6,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 301.4817,
      "time_ms_std": null,
      "ops_sec_mean": 3.32,
      "memory_kb_mean": -1116.29,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 105.5646,
      "time_ms_std": null,
      "ops_sec_mean": 9.47,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "random",
      "runs": 7,
      "time_ms_mean": 129.5496,
      "time_ms_std": null,
      "ops_sec_mean": 7.72,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 19.2636,
      "time_ms_std": null,
      "ops_sec_mean": 51.91,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 212.0301,
      "time_ms_std": null,
      "ops_sec_mean": 4.72,
      "memory_kb_mean": -1116.29,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 32.5439,
      "time_ms_std": null,
      "ops_sec_mean": 30.73,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "sorted",
      "runs": 7,
      "time_ms_mean": 53.4203,
      "time_ms_std": null,
      "ops_sec_mean": 18.72,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 19.4037,
      "time_ms_std": null,
      "ops_sec_mean": 51.54,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 207.853,
      "time_ms_std": null,
      "ops_sec_mean": 4.81,
      "memory_kb_mean": -1116.29,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 36.1149,
      "time_ms_std": null,
      "ops_sec_mean": 27.69,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "reversed",
      "runs": 7,
      "time_ms_mean": 54.9267,
      "time_ms_std": null,
      "ops_sec_mean": 18.21,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 57.7211,
      "time_ms_std": null,
      "ops_sec_mean": 17.32,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 214.7772,
      "time_ms_std": null,
      "ops_sec_mean": 4.66,
      "memory_kb_mean": -1116.29,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 34.9135,
      "time_ms_std": null,
      "ops_sec_mean": 28.64,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "nearlySorted",
      "runs": 7,
      "time_ms_mean": 55.4394,
      "time_ms_std": null,
      "ops_sec_mean": 18.04,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 100.6862,
      "time_ms_std": null,
      "ops_sec_mean": 9.93,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 233.7075,
      "time_ms_std": null,
      "ops_sec_mean": 4.28,
      "memory_kb_mean": -1116.29,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 55.6437,
      "time_ms_std": null,
      "ops_sec_mean": 17.97,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "duplicates",
      "runs": 7,
      "time_ms_mean": 75.4837,
      "time_ms_std": null,
      "ops_sec_mean": 13.25,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 96.1423,
      "time_ms_std": null,
      "ops_sec_mean": 10.4,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 220.976,
      "time_ms_std": null,
      "ops_sec_mean": 4.53,
      "memory_kb_mean": -1116.29,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 51.4602,
      "time_ms_std": null,
      "ops_sec_mean": 19.43,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "fewUnique",
      "runs": 7,
      "time_ms_mean": 71.8256,
      "time_ms_std": null,
      "ops_sec_mean": 13.92,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "array-sort-built-in",
      "displayName": "array-sort-built-in",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 18.3109,
      "time_ms_std": null,
      "ops_sec_mean": 54.61,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "merge-sort",
      "displayName": "merge-sort",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 203.5561,
      "time_ms_std": null,
      "ops_sec_mean": 4.91,
      "memory_kb_mean": -1116.29,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-recursive",
      "displayName": "quick-sort-recursive",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 47.1359,
      "time_ms_std": null,
      "ops_sec_mean": 21.22,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    },
    {
      "algorithm": "quick-sort-iterative",
      "displayName": "quick-sort-iterative",
      "category": "sorting",
      "input_size": 1000000,
      "input_type": "uniform",
      "runs": 7,
      "time_ms_mean": 66.9287,
      "time_ms_std": null,
      "ops_sec_mean": 14.94,
      "memory_kb_mean": -1116.07,
      "__sourceFile": "exp-1"
    }
  ]
}